### ISSUE TITLE
extract/unpack does not preserve executable files

### ISSUE THREAD

**Issue by bitc** [haskell/tar#25]
When I run `extract` or `unpack` on a tarball, it extracts all of the files, but does not properly set the "executable" bit on executable files.

I have to manually run `chmod +x` on them after they are extracted by tar to be able to run them.

**Comment by bitc** [comment]
This looks relevant: https://github.com/snoyberg/keter/commit/e0fa8d7baca298097cde92e200db5d1993c5212b

They switched from using `unpack` to a custom function that preserves the permissions.

**Comment by tmortiboy** [comment]
I came across the same issue.
I was just in the middle of creating a fix to submit using `setPermissions` from `System.Directory`, but  using `setFileMode` from `System.PosixCompat.Files` uses the permissions directly without need for computation.

**Comment by tmortiboy** [comment]
After a little investigation, `setFileMode` just calls `setPermissions` under the hood, so will be best to just use that instead of bringing in new dependencies.
Currently have the changes on a [fork](https://github.com/haskell/tar/compare/master...tmortiboy:master), but cant get the property tests to pass (even before I made my changes).

**Comment by afranchuk** [comment]
Any word on whether this will be merged soon?

**Comment by hasufell** [comment]
This is fixed in tar-bytestring (if you don't mind excluding windows support and bytestring based filepaths): https://github.com/hasufell/tar-bytestring/commit/ce13c5033f101dfb97649b47135e7398ec888afb
