### ISSUE TITLE
Bad parse of entryTarPath

### ISSUE THREAD

**Issue by brandon-leapyear** [haskell/tar#35]
When extracting [postgresql 9.6.9](https://www.enterprisedb.com/download-postgresql-binaries), there's a failure:
```
pgsql/pgAdmin 4/web/pgadmin/browser/server_groups/servers/resource_groups/templates/resource_groups/: openBinaryFile: inappropriate type (Is a directory)
```
After some inspection in GHCi, I found
```
ghci> entries <- Tar.read . GZip.decompress =<< BS.readFile "..."
ghci> let entries' = Tar.foldEntries (:) [] (const []) entries
ghci> let path = "pgsql/pgAdmin 4/web/pgadmin/browser/server_groups/servers/resource_groups/templates/resource_groups/"
ghci> length $ filter ((== path) . Tar.entryPath) entries'
8
```
In other words, there are 8 `Entry` objects with the same path as their directory. I suspect there's a bug that doesn't parse or concatenate the TarPath name/prefix correctly.

**Comment by hasufell** [comment]
There are two issues here:

1. the paths you are referring to are over-long, see https://github.com/haskell/tar/pull/50
2. There seem to be more errors due to symlinks that are handled incorrectly, when a symlink points to a directory (as opposed to a file). tar emulates symlinks and just copies them. This will fail for directories: https://github.com/haskell/tar/blob/a0d722c1f6052bf144017d131a715ea1ae599964/Codec/Archive/Tar/Unpack.hs#L110-L113 ...a patch is in the same PR as above: https://github.com/haskell/tar/pull/50/commits/499db333b4a4432bcc88e3a1a014565e803564e1

----

So, with the above PR, I can unpack said tarball.
