### ISSUE TITLE
packFileEntry leaks handles

### ISSUE THREAD

**Issue by Gabriella439** [haskell/tar#56]
`Codec.Archive.Tar.Pack.packFileEntry` leaks `Handle`s because it doesn't use `System.IO.withBinaryFile`.  Instead it uses `System.IO.openBinaryFile`:

https://github.com/haskell/tar/blob/557014f2a441e3b9372e5d30b437fe50cdf190bc/Codec/Archive/Tar/Pack.hs#L113

… without a matching `System.IO.hClose`.  We ran into this issue when attempting to create an archive with a large number of files, leading to the following error:

```
openBinaryFile: resource exhausted (Too many open files)
```

**Comment by Bodigrim** [comment]
Fixed in ae872fc7e4e8d7aca22e77dc710830567fe10247.

**Comment by Bodigrim** [comment]
Reopening, since my fix is forcing entire lazy `ByteString` into the memory which was not the case before. (I was fooled by `BS.*` instead of `LBS.*`)

@Gabriella439 I'm not sure how `withBinaryFile` would help. This library heavily (ab)uses lazy IO: the handle is supposed to be closed once garbage collected, but we cannot close it earlier without allocating entire content of the file in memory at once, which might not be an option. 

(I'm fairly illiterate in the resource management, feel free to correct me if I'm talking nonsense)

**Comment by Gabriella439** [comment]
Yeah, you don't have to use `withBinaryFile`.  I'm more interested in fixing the handle leak regardless of the solution

**Comment by Bodigrim** [comment]
I made another attempt in 0faa59b4220aa61b582cf7501dc764b6ad099757. I guess it's as good as it gets in a library, based on lazy I/O.

**Comment by hasufell** [comment]
Can this be closed?

**Comment by Bodigrim** [comment]
> Can this be closed?

It is still possible to trigger the issue by creating a long sequence of `Entries` for large files and forcing them by, say, `checkSecurity`. However I do not see how to make `tar` fully bullet-proof against it, and adding `packAndCheck` / `unpackAndCheck` should alleviate the pain for the majority of users. Documentation PRs to educate users are welcome, but otherwise closing.
